
name: Release Charts

on:
  push:
    branches:
      - main

permissions:
  contents: write
jobs:

    lint:
        uses: ./.github/workflows/kube-static-analysis.yaml
        with:
            charts: '["checkov", "tfsec", "terrascan", "tfscan"]'
            skip: '["kubesec1"]'
            
# jobs:
# static-analysis:
#     # runs-on: ubuntu-latest
#     name: Static Analysis
#     steps:
#     - uses: actions/checkout@v3
#     - uses: ./.github/actions/lint