name: Release Charts

# on:
#   push:
#     branches:
#       - main


on:
  workflow_run:
    workflows: ["Kube static analysis"]
    branches: [main]
    types: 
      - completed      

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    if: github.event.workflow_run.conclusion == 'success'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      # - name: Lint
      #   working-directory: charts
      #   run: find .  -maxdepth 1 -mindepth 1 -exec helm datree test {} \;  

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
